---
# tasks file for cassandra_3
# https://cassandra.apache.org/download/
# echo "deb https://downloads.apache.org/cassandra/debian 311x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
- name: "Add the Apache repository of Cassandra to /etc/apt/sources.list.d/cassandra.sources.list"
  apt_repository:
    repo: deb https://downloads.apache.org/cassandra/debian 311x main
    state: present
    update_cache: no
    filename: cassandra311

- name: "Add & update the Apache repository of Cassandra"
  apt_key:
    url: https://downloads.apache.org/cassandra/KEYS
    state: present

- name: "Download & install Cassandra"
  apt:
    name: cassandra
    update_cache: yes
