---
# tasks file for cassandra_3
# https://cassandra.apache.org/download/
#- name: "Add & update the Apache repository of Cassandra"
#  command: "{{ item }}"
#  with_items:
#    - echo "deb https://downloads.apache.org/cassandra/debian 311x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
#    - curl https://downloads.apache.org/cassandra/KEYS | sudo apt-key add -

- name: "Add the Apache repository of Cassandra to /etc/apt/sources.list.d/cassandra.sources.list"
  command: "{{ item }}"
  with_items:
    - echo "deb https://downloads.apache.org/cassandra/debian 311x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list

- name: "Add & update the Apache repository of Cassandra"
  apt_key:
    url: https://downloads.apache.org/cassandra/KEYS
    state: present

- name: "Download & install Cassandra"
  apt:
    name: cassandra
    update_cache: yes
